//>>built
require({cache:{"mijit/_TemplatedMixin":function(){define("mijit/_TemplatedMixin","dojo/_base/lang,dojo/touch,./_WidgetBase,dojo/string,dojo/cache,dojo/_base/array,dojo/_base/declare,dojo/dom-construct,dojo/sniff,dojo/_base/unload".split(","),function(k,l,h,j,a,b,f,e,c,d){var r=f("dijit._TemplatedMixin",null,{templateString:null,templatePath:null,_skipNodeCache:!1,_earlyTemplatedStartup:!1,constructor:function(){this._attachPoints=[];this._attachEvents=[]},_stringRepl:function(a){var c=this.declaredClass,
b=this;return j.substitute(a,this,function(a,d){"!"==d.charAt(0)&&(a=k.getObject(d.substr(1),!1,b));if("undefined"==typeof a)throw Error(c+" template:"+d);return null==a?"":"!"==d.charAt(0)?a:a.toString().replace(/"/g,"&quot;")},this)},buildRendering:function(){if(!this.templateString)this.templateString=a(this.templatePath,{sanitize:!0});var c=r.getCachedTemplate(this.templateString,this._skipNodeCache,this.ownerDocument),b;if(k.isString(c)){if(b=e.toDom(this._stringRepl(c),this.ownerDocument),1!=
b.nodeType)throw Error("Invalid template: "+c);}else b=c.cloneNode(!0);this.domNode=b;this.inherited(arguments);this._attachTemplateNodes(b,function(a,c){return a.getAttribute(c)});this._beforeFillContent();this._fillContent(this.srcNodeRef)},_beforeFillContent:function(){},_fillContent:function(a){var c=this.containerNode;if(a&&c)for(;a.hasChildNodes();)c.appendChild(a.firstChild)},_attachTemplateNodes:function(a,c){for(var b=k.isArray(a)?a:a.all||a.getElementsByTagName("*"),d=k.isArray(a)?0:-1;0>
d||b[d];d++){var f=-1==d?a:b[d];if(!this.widgetsInTemplate||!c(f,"dojoType")&&!c(f,"data-dojo-type")){var e=c(f,"dojoAttachPoint")||c(f,"data-dojo-attach-point");if(e)for(var r=e.split(/\s*,\s*/);e=r.shift();)k.isArray(this[e])?this[e].push(f):this[e]=f,this._attachPoints.push(e);if(e=c(f,"dojoAttachEvent")||c(f,"data-dojo-attach-event"))for(var r=e.split(/\s*,\s*/),j=k.trim;e=r.shift();)if(e){var h=null;-1!=e.indexOf(":")?(h=e.split(":"),e=j(h[0]),h=j(h[1])):e=j(e);h||(h=e);this._attachEvents.push(this.connect(f,
l[e]||e,h))}}}},destroyRendering:function(){b.forEach(this._attachPoints,function(a){delete this[a]},this);this._attachPoints=[];b.forEach(this._attachEvents,this.disconnect,this);this._attachEvents=[];this.inherited(arguments)}});r._templateCache={};r.getCachedTemplate=function(a,c,b){var d=r._templateCache,f=a,h=d[f];if(h){try{if(!h.ownerDocument||h.ownerDocument==(b||document))return h}catch(k){}e.destroy(h)}a=j.trim(a);if(c||a.match(/\$\{([^\}]+)\}/g))return d[f]=a;c=e.toDom(a,b);if(1!=c.nodeType)throw Error("Invalid template: "+
a);return d[f]=c};c("ie")&&d.addOnWindowUnload(function(){var a=r._templateCache,c;for(c in a){var b=a[c];"object"==typeof b&&e.destroy(b);delete a[c]}});k.extend(h,{dojoAttachEvent:"",dojoAttachPoint:""});return r})},"dojo/touch":function(){define("dojo/touch","./_base/kernel,./_base/lang,./aspect,./dom,./on,./has,./mouse,./domReady,./_base/window".split(","),function(k,l,h,j,a,b,f,e,c){function d(c){return function(b,d){return a(b,c,d)}}var h=b("touch"),r=!1;b("ios")&&(b=navigator.userAgent.match(/OS ([\d_]+)/)?
RegExp.$1:"1",r=5>parseFloat(b.replace(/_/,".").replace(/_/g,"")));var B,u;h&&(e(function(){u=c.body();c.doc.addEventListener("touchstart",function(c){var b=u;u=c.target;a.emit(b,"dojotouchout",{target:b,relatedTarget:u,bubbles:!0});a.emit(u,"dojotouchover",{target:u,relatedTarget:b,bubbles:!0})},!0);a(c.doc,"touchmove",function(b){if((b=c.doc.elementFromPoint(b.pageX-(r?0:c.global.pageXOffset),b.pageY-(r?0:c.global.pageYOffset)))&&u!==b)a.emit(u,"dojotouchout",{target:u,relatedTarget:b,bubbles:!0}),
a.emit(b,"dojotouchover",{target:b,relatedTarget:u,bubbles:!0}),u=b})}),B=function(b,d){return a(c.doc,"touchmove",function(a){(b===c.doc||j.isDescendant(u,b))&&d.call(this,l.mixin({},a,{target:u,touches:a.touches,preventDefault:function(){a.preventDefault()},stopPropagation:function(){a.stopPropagation()}}))})});f={press:d(h?"touchstart":"mousedown"),move:h?B:d("mousemove"),release:d(h?"touchend":"mouseup"),cancel:h?d("touchcancel"):f.leave,over:d(h?"dojotouchover":"mouseover"),out:d(h?"dojotouchout":
"mouseout"),enter:f._eventHandler(h?"dojotouchover":"mouseover"),leave:f._eventHandler(h?"dojotouchout":"mouseout")};return k.touch=f})},"mijit/_WidgetBase":function(){define("mijit/_WidgetBase","require,dojo/_base/array,dojo/aspect,dojo/_base/config,dojo/_base/connect,dojo/_base/declare,dojo/dom,dojo/dom-attr,dojo/dom-class,dojo/dom-construct,dojo/dom-geometry,dojo/dom-style,dojo/has,dojo/_base/kernel,dojo/_base/lang,dojo/on,dojo/ready,dojo/Stateful,dojo/topic,dojo/_base/window,./Destroyable,./registry".split(","),
function(k,l,h,j,a,b,f,e,c,d,r,B,u,I,p,q,C,D,F,y,G,v){function H(g){return function(a){e[a?"set":"remove"](this.domNode,g,a);this._set(g,a)}}u.add("dijit-legacy-requires",!I.isAsync);u("dijit-legacy-requires")&&C(0,function(){k(["dijit/_base/manager"])});var K={};return b("dijit._WidgetBase",[D,G],{id:"",_setIdAttr:"domNode",lang:"",_setLangAttr:H("lang"),dir:"",_setDirAttr:H("dir"),textDir:"","class":"",_setClassAttr:{node:"domNode",type:"class"},style:"",title:"",tooltip:"",baseClass:"",srcNodeRef:null,
domNode:null,containerNode:null,ownerDocument:null,_setOwnerDocumentAttr:function(g){this._set("ownerDocument",g)},attributeMap:{},_blankGif:j.blankGif||k.toUrl("dojo/resources/blank.gif"),postscript:function(g,a){this.create(g,a)},create:function(g,a){this.srcNodeRef=f.byId(a);this._connects=[];this._supportingWidgets=[];if(this.srcNodeRef&&"string"==typeof this.srcNodeRef.id)this.id=this.srcNodeRef.id;if(g)this.params=g,p.mixin(this,g);this.postMixInProperties();if(!this.id)this.id=v.getUniqueId(this.declaredClass.replace(/\./g,
"_")),this.params&&delete this.params.id;this.ownerDocument=this.ownerDocument||(this.srcNodeRef?this.srcNodeRef.ownerDocument:y.doc);this.ownerDocumentBody=y.body(this.ownerDocument);v.add(this);this.buildRendering();var c;if(this.domNode){this._applyAttributes();var b=this.srcNodeRef;b&&b.parentNode&&this.domNode!==b&&(b.parentNode.replaceChild(this.domNode,b),c=!0);this.domNode.setAttribute("widgetId",this.id)}this.postCreate();c&&delete this.srcNodeRef;this._created=!0},_applyAttributes:function(){var g=
this.constructor,a=g._setterAttrs;if(!a){var a=g._setterAttrs=[],b;for(b in this.attributeMap)a.push(b);var g=g.prototype,c;for(c in g)c in this.attributeMap||"_set"+c.replace(/^[a-z]|-[a-zA-Z]/g,function(g){return g.charAt(g.length-1).toUpperCase()})+"Attr"in g&&a.push(c)}var d={},v;for(v in this.params||{})d[v]=this[v];l.forEach(a,function(g){g in d||this[g]&&this.set(g,this[g])},this);for(v in d)this.set(v,d[v])},postMixInProperties:function(){},buildRendering:function(){if(!this.domNode)this.domNode=
this.srcNodeRef||this.ownerDocument.createElement("div");if(this.baseClass){var g=this.baseClass.split(" ");this.isLeftToRight()||(g=g.concat(l.map(g,function(g){return g+"Rtl"})));c.add(this.domNode,g)}},postCreate:function(){},startup:function(){if(!this._started)this._started=!0,l.forEach(this.getChildren(),function(g){if(!g._started&&!g._destroyed&&p.isFunction(g.startup))g.startup(),g._started=!0})},destroyRecursive:function(g){this._beingDestroyed=!0;this.destroyDescendants(g);this.destroy(g)},
destroy:function(g){function a(c){c.destroyRecursive?c.destroyRecursive(g):c.destroy&&c.destroy(g)}this._beingDestroyed=!0;this.uninitialize();l.forEach(this._connects,p.hitch(this,"disconnect"));l.forEach(this._supportingWidgets,a);this.domNode&&l.forEach(v.findWidgets(this.domNode,this.containerNode),a);this.destroyRendering(g);v.remove(this.id);this._destroyed=!0},destroyRendering:function(g){this.bgIframe&&(this.bgIframe.destroy(g),delete this.bgIframe);this.domNode&&(g?e.remove(this.domNode,
"widgetId"):d.destroy(this.domNode),delete this.domNode);this.srcNodeRef&&(g||d.destroy(this.srcNodeRef),delete this.srcNodeRef)},destroyDescendants:function(g){l.forEach(this.getChildren(),function(a){a.destroyRecursive&&a.destroyRecursive(g)})},uninitialize:function(){return!1},_setStyleAttr:function(g){var a=this.domNode;p.isObject(g)?B.set(a,g):a.style.cssText=a.style.cssText?a.style.cssText+("; "+g):g;this._set("style",g)},_attrToDom:function(g,a,b){b=3<=arguments.length?b:this.attributeMap[g];
l.forEach(p.isArray(b)?b:[b],function(b){var d=this[b.node||b||"domNode"];switch(b.type||"attribute"){case "attribute":p.isFunction(a)&&(a=p.hitch(this,a));b=b.attribute?b.attribute:/^on[A-Z][a-zA-Z]*$/.test(g)?g.toLowerCase():g;d.tagName?e.set(d,b,a):d.set(b,a);break;case "innerText":d.innerHTML="";d.appendChild(this.ownerDocument.createTextNode(a));break;case "innerHTML":d.innerHTML=a;break;case "class":c.replace(d,a,this[g])}},this)},get:function(g){var a=this._getAttrNames(g);return this[a.g]?
this[a.g]():this[g]},set:function(a,b){if("object"===typeof a){for(var c in a)this.set(c,a[c]);return this}c=this._getAttrNames(a);var d=this[c.s];if(p.isFunction(d))var v=d.apply(this,Array.prototype.slice.call(arguments,1));else{var d=this.focusNode&&!p.isFunction(this.focusNode)?"focusNode":"domNode",f=this[d]&&this[d].tagName,e;if(e=f)if(!(e=K[f])){e=this[d];var H={},i;for(i in e)H[i.toLowerCase()]=!0;e=K[f]=H}i=e;c=a in this.attributeMap?this.attributeMap[a]:c.s in this?this[c.s]:i&&c.l in i&&
"function"!=typeof b||/^aria-|^data-|^role$/.test(a)?d:null;null!=c&&this._attrToDom(a,b,c);this._set(a,b)}return v||this},_attrPairNames:{},_getAttrNames:function(a){var b=this._attrPairNames;if(b[a])return b[a];var c=a.replace(/^[a-z]|-[a-zA-Z]/g,function(a){return a.charAt(a.length-1).toUpperCase()});return b[a]={n:a+"Node",s:"_set"+c+"Attr",g:"_get"+c+"Attr",l:c.toLowerCase()}},_set:function(a,b){var c=this[a];this[a]=b;this._created&&b!==c&&(this._watchCallbacks&&this._watchCallbacks(a,c,b),
this.emit("attrmodified-"+a,{detail:{prevValue:c,newValue:b}}))},emit:function(a,b,c){b=b||{};if(void 0===b.bubbles)b.bubbles=!0;if(void 0===b.cancelable)b.cancelable=!0;if(!b.detail)b.detail={};b.detail.widget=this;var d,v=this["on"+a];v&&(d=v.apply(this,c?c:[b]));this._started&&!this._beingDestroyed&&q.emit(this.domNode,a.toLowerCase(),b);return d},on:function(a,b){var c=this._onMap(a);return c?h.after(this,c,b,!0):this.own(q(this.domNode,a,b))[0]},_onMap:function(a){var b=this.constructor,c=b._onMap;
if(!c){var c=b._onMap={},d;for(d in b.prototype)/^on/.test(d)&&(c[d.replace(/^on/,"").toLowerCase()]=d)}return c["string"==typeof a&&a.toLowerCase()]},toString:function(){return"[Widget "+this.declaredClass+", "+(this.id||"NO ID")+"]"},getChildren:function(){return this.containerNode?v.findWidgets(this.containerNode):[]},getParent:function(){return v.getEnclosingWidget(this.domNode.parentNode)},connect:function(b,c,d){return this.own(a.connect(b,c,this,d))[0]},disconnect:function(a){a.remove()},subscribe:function(a,
b){return this.own(F.subscribe(a,p.hitch(this,b)))[0]},unsubscribe:function(a){a.remove()},isLeftToRight:function(){return this.dir?"ltr"==this.dir:r.isBodyLtr(this.ownerDocument)},isFocusable:function(){return this.focus&&"none"!=B.get(this.domNode,"display")},placeAt:function(a,b){var c=!a.tagName&&v.byId(a);c&&c.addChild&&(!b||"number"===typeof b)?c.addChild(this,b):(c=c?c.containerNode&&!/after|before|replace/.test(b||"")?c.containerNode:c.domNode:f.byId(a,this.ownerDocument),d.place(this.domNode,
c,b),!this._started&&(this.getParent()||{})._started&&this.startup());return this},getTextDir:function(a,b){return b},applyTextDir:function(){},defer:function(a,b){var c=setTimeout(p.hitch(this,function(){c=null;this._destroyed||p.hitch(this,a)()}),b||0);return{remove:function(){c&&(clearTimeout(c),c=null);return null}}}})})},"dojo/Stateful":function(){define("dojo/Stateful",["./_base/declare","./_base/lang","./_base/array","dojo/when"],function(k,l,h,j){return k("dojo.Stateful",null,{_attrPairNames:{},
_getAttrNames:function(a){var b=this._attrPairNames;return b[a]?b[a]:b[a]={s:"_"+a+"Setter",g:"_"+a+"Getter"}},postscript:function(a){a&&this.set(a)},_get:function(a,b){return"function"===typeof this[b.g]?this[b.g]():this[a]},get:function(a){return this._get(a,this._getAttrNames(a))},set:function(a,b){if("object"===typeof a){for(var f in a)a.hasOwnProperty(f)&&"_watchCallbacks"!=f&&this.set(f,a[f]);return this}f=this._getAttrNames(a);var e=this._get(a,f);f=this[f.s];var c;"function"===typeof f?c=
f.apply(this,Array.prototype.slice.call(arguments,1)):this[a]=b;if(this._watchCallbacks){var d=this;j(c,function(){d._watchCallbacks(a,e,b)})}return this},_changeAttrValue:function(a,b){var f=this.get(a);this[a]=b;this._watchCallbacks&&this._watchCallbacks(a,f,b);return this},watch:function(a,b){var f=this._watchCallbacks;if(!f)var e=this,f=this._watchCallbacks=function(a,b,c,d){var h=function(d){if(d)for(var d=d.slice(),f=0,h=d.length;f<h;f++)d[f].call(e,a,b,c)};h(f["_"+a]);d||h(f["*"])};!b&&"function"===
typeof a?(b=a,a="*"):a="_"+a;var c=f[a];"object"!==typeof c&&(c=f[a]=[]);c.push(b);var d={};d.unwatch=d.remove=function(){var a=h.indexOf(c,b);-1<a&&c.splice(a,1)};return d}})})},"mijit/Destroyable":function(){define("mijit/Destroyable",["dojo/_base/array","dojo/aspect","dojo/_base/declare"],function(k,l,h){return h("dijit.Destroyable",null,{destroy:function(){this._destroyed=!0},own:function(){k.forEach(arguments,function(h){var a="destroyRecursive"in h?"destroyRecursive":"destroy"in h?"destroy":
"remove",b=l.before(this,"destroy",function(b){h[a](b)}),f=l.after(h,a,function(){b.remove();f.remove()},!0)},this);return arguments}})})},"mijit/registry":function(){define("mijit/registry",["dojo/_base/array","dojo/sniff","dojo/_base/unload","dojo/_base/window","./main"],function(k,l,h,j,a){var b={},f={},e={length:0,add:function(a){if(f[a.id])throw Error("Tried to register widget with id=="+a.id+" but that id is already registered");f[a.id]=a;this.length++},remove:function(a){f[a]&&(delete f[a],
this.length--)},byId:function(a){return"string"==typeof a?f[a]:a},byNode:function(a){return f[a.getAttribute("widgetId")]},toArray:function(){var a=[],b;for(b in f)a.push(f[b]);return a},getUniqueId:function(c){var d;do d=c+"_"+(c in b?++b[c]:b[c]=0);while(f[d]);return"dijit"==a._scopeName?d:a._scopeName+"_"+d},findWidgets:function(a,b){function e(a){for(a=a.firstChild;a;a=a.nextSibling)if(1==a.nodeType){var c=a.getAttribute("widgetId");c?(c=f[c])&&h.push(c):a!==b&&e(a)}}var h=[];e(a);return h},_destroyAll:function(){a._curFocus=
null;a._prevFocus=null;a._activeStack=[];k.forEach(e.findWidgets(j.body()),function(a){a._destroyed||(a.destroyRecursive?a.destroyRecursive():a.destroy&&a.destroy())})},getEnclosingWidget:function(a){for(;a;){var b=a.getAttribute&&a.getAttribute("widgetId");if(b)return f[b];a=a.parentNode}return null},_hash:f};return a.registry=e})},"mijit/main":function(){define("mijit/main",["dojo/_base/kernel"],function(k){return k.dijit})},"dojo/cache":function(){define("dojo/cache",["./_base/kernel","./text"],
function(k){return k.cache})},"dojo/text":function(){define("dojo/text",["./_base/kernel","require","./has","./_base/xhr"],function(k,l,h,j){var a;a=function(a,b,c){j("GET",{url:a,sync:!!b,load:c,headers:k.config.textPluginHeaders||{}})};var b={},f=function(a){if(a){var a=a.replace(/^\s*<\?xml(\s)+version=[\'\"](\d)*.(\d)*[\'\"](\s)*\?>/im,""),b=a.match(/<body[^>]*>\s*([\s\S]+)\s*<\/body>/im);b&&(a=b[1])}else a="";return a},e={},c={};k.cache=function(c,e,h){var j;"string"==typeof c?/\//.test(c)?(j=
c,h=e):j=l.toUrl(c.replace(/\./g,"/")+(e?"/"+e:"")):(j=c+"",h=e);c=void 0!=h&&"string"!=typeof h?h.value:h;h=h&&h.sanitize;if("string"==typeof c)return b[j]=c,h?f(c):c;if(null===c)return delete b[j],null;j in b||a(j,!0,function(a){b[j]=a});return h?f(b[j]):b[j]};return{dynamic:!0,normalize:function(a,b){var c=a.split("!"),e=c[0];return(/^\./.test(e)?b(e):e)+(c[1]?"!"+c[1]:"")},load:function(d,h,j){var d=d.split("!"),k=1<d.length,l=d[0],p=h.toUrl(d[0]),d="url:"+p,q=e,C=function(a){j(k?f(a):a)};l in
b?q=b[l]:d in h.cache?q=h.cache[d]:p in b&&(q=b[p]);if(q===e)if(c[p])c[p].push(C);else{var D=c[p]=[C];a(p,!h.async,function(a){b[l]=b[p]=a;for(var d=0;d<D.length;)D[d++](a);delete c[p]})}else C(q)}}})},"mijit/_WidgetsInTemplateMixin":function(){define("mijit/_WidgetsInTemplateMixin",["dojo/_base/array","dojo/_base/declare","dojo/parser"],function(k,l,h){return l("dijit._WidgetsInTemplateMixin",null,{_earlyTemplatedStartup:!1,widgetsInTemplate:!0,_beforeFillContent:function(){if(this.widgetsInTemplate){var j=
this._startupWidgets=h.parse(this.domNode,{noStart:!this._earlyTemplatedStartup,template:!0,inherited:{dir:this.dir,lang:this.lang,textDir:this.textDir},propsThis:this,scope:"dojo"});if(!j.isFulfilled())throw Error(this.declaredClass+": parser returned unfilled promise (probably waiting for module auto-load), unsupported by _WidgetsInTemplateMixin.   Must pre-load all supporting widgets before instantiation.");this._attachTemplateNodes(j,function(a,b){return a[b]})}},startup:function(){k.forEach(this._startupWidgets,
function(h){h&&!h._started&&h.startup&&h.startup()});this.inherited(arguments)}})})},"dojo/parser":function(){define("dojo/parser","require,./_base/kernel,./_base/lang,./_base/array,./_base/config,./_base/html,./_base/window,./_base/url,./_base/json,./aspect,./date/stamp,./Deferred,./has,./query,./on,./ready".split(","),function(k,l,h,j,a,b,f,e,c,d,r,B,u,I,p,q){function C(a){var b=a._nameCaseMap,c=a.prototype;if(!b||b._extendCnt<F){var b=a._nameCaseMap={},g;for(g in c)"_"!==g.charAt(0)&&(b[g.toLowerCase()]=
g);b._extendCnt=F}return b}function D(a){var b=a.join();if(!y[b]){for(var c=[],g=0,d=a.length;g<d;g++){var e=a[g];c[c.length]=y[e]=y[e]||h.getObject(e)||~e.indexOf("/")&&k(e)}a=c.shift();y[b]=c.length?a.createSubclass?a.createSubclass(c):a.extend.apply(a,c):a}return y[b]}var F=0;d.after(h,"extend",function(){F++},!0);var y={},G={_clearCache:function(){F++;y={}},_functionFromScript:function(a,b){var c="",g="",d=a.getAttribute(b+"args")||a.getAttribute("args"),e=a.getAttribute("with"),d=(d||"").split(/\s*,\s*/);
e&&e.length&&j.forEach(e.split(/\s*,\s*/),function(a){c+="with("+a+"){";g+="}"});return new Function(d,c+a.innerHTML+g)},instantiate:function(a,b,c){var b=b||{},c=c||{},g=(c.scope||l._scopeName)+"Type",d="data-"+(c.scope||l._scopeName)+"-",e=d+"type",h=d+"mixins",f=[];j.forEach(a,function(a){var c=g in b?b[g]:a.getAttribute(e)||a.getAttribute(g);if(c){var d=a.getAttribute(h),c=d?[c].concat(d.split(/\s*,\s*/)):[c];f.push({node:a,types:c})}});return this._instantiate(f,b,c)},_instantiate:function(a,
b,c){a=j.map(a,function(a){var d=a.ctor||D(a.types);if(!d)throw Error("Unable to resolve constructor for: '"+a.types.join()+"'");return this.construct(d,a.node,b,c,a.scripts,a.inherited)},this);!b._started&&!c.noStart&&j.forEach(a,function(a){"function"===typeof a.startup&&!a._started&&a.startup()});return a},construct:function(a,b,f,g,k,z){var v;var q=a&&a.prototype,g=g||{},s={};g.defaults&&h.mixin(s,g.defaults);z&&h.mixin(s,z);var A;u("dom-attributes-explicit")?A=b.attributes:u("dom-attributes-specified-flag")?
A=j.filter(b.attributes,function(a){return a.specified}):(z=(/^input$|^img$/i.test(b.nodeName)?b:b.cloneNode(!1)).outerHTML.replace(/=[^\s"']+|="[^"]*"|='[^']*'/g,"").replace(/^\s*<[a-zA-Z0-9]*\s*/,"").replace(/\s*>.*$/,""),A=j.map(z.split(/\s+/),function(a){var c=a.toLowerCase();return{name:a,value:"LI"==b.nodeName&&"value"==a||"enctype"==c?b.getAttribute(c):b.getAttributeNode(c).value}}));var m=g.scope||l._scopeName,z="data-"+m+"-",n={};"dojo"!==m&&(n[z+"props"]="data-dojo-props",n[z+"type"]="data-dojo-type",
n[z+"mixins"]="data-dojo-mixins",n[m+"type"]="dojoType",n[z+"id"]="data-dojo-id");for(var m=0,i,E=[],J,t;i=A[m++];){var o=i.name,w=o.toLowerCase();i=i.value;switch(n[w]||w){case "data-dojo-type":case "dojotype":case "data-dojo-mixins":break;case "data-dojo-props":t=i;break;case "data-dojo-id":case "jsid":J=i;break;case "data-dojo-attach-point":case "dojoattachpoint":s.dojoAttachPoint=i;break;case "data-dojo-attach-event":case "dojoattachevent":s.dojoAttachEvent=i;break;case "class":s["class"]=b.className;
break;case "style":s.style=b.style&&b.style.cssText;break;default:if(o in q||(o=C(a)[w]||o),o in q)switch(typeof q[o]){case "string":s[o]=i;break;case "number":s[o]=i.length?Number(i):NaN;break;case "boolean":s[o]="false"!=i.toLowerCase();break;case "function":s[o]=""===i||-1!=i.search(/[^\w\.]+/i)?new Function(i):h.getObject(i,!1)||new Function(i);E.push(o);break;default:w=q[o],s[o]=w&&"length"in w?i?i.split(/\s*,\s*/):[]:w instanceof Date?""==i?new Date(""):"now"==i?new Date:r.fromISOString(i):
w instanceof e?l.baseUrl+i:c.fromJson(i)}else s[o]=i}}for(m=0;m<E.length;m++)A=E[m].toLowerCase(),b.removeAttribute(A),b[A]=null;if(t)try{t=c.fromJson.call(g.propsThis,"{"+t+"}"),h.mixin(s,t)}catch(B){throw Error(B.toString()+" in data-dojo-props='"+t+"'");}h.mixin(s,f);k||(k=a&&(a._noScript||q._noScript)?[]:I("> script[type^='dojo/']",b));f=[];g=[];t=[];E=[];if(k)for(m=0;m<k.length;m++){var x=k[m];b.removeChild(x);A=x.getAttribute(z+"event")||x.getAttribute("event");n=x.getAttribute(z+"prop");o=
x.getAttribute(z+"method");w=x.getAttribute(z+"advice");i=x.getAttribute("type");x=this._functionFromScript(x,z);A?"dojo/connect"==i?f.push({method:A,func:x}):"dojo/on"==i?E.push({event:A,func:x}):s[A]=x:"dojo/aspect"==i?f.push({method:o,advice:w,func:x}):"dojo/watch"==i?t.push({prop:n,func:x}):g.push(x)}v=(k=a.markupFactory||q.markupFactory)?k(s,b,a):new a(s,b),a=v;J&&h.setObject(J,a);for(m=0;m<f.length;m++)d[f[m].advice||"after"](a,f[m].method,h.hitch(a,f[m].func),!0);for(m=0;m<g.length;m++)g[m].call(a);
for(m=0;m<t.length;m++)a.watch(t[m].prop,t[m].func);for(m=0;m<E.length;m++)p(a,E[m].event,E[m].func);return a},scan:function(a,b){function c(a){if(!a.inherited){a.inherited={};var b=a.node,d=c(a.parent),b={dir:b.getAttribute("dir")||d.dir,lang:b.getAttribute("lang")||d.lang,textDir:b.getAttribute(m)||d.textDir},e;for(e in b)b[e]&&(a.inherited[e]=b[e])}return a.inherited}var d=[],e=[],f={},h=(b.scope||l._scopeName)+"Type",s="data-"+(b.scope||l._scopeName)+"-",p=s+"type",m=s+"textdir",s=s+"mixins",
n=a.firstChild,i=b.inherited;if(!i){var r=function(a,b){return a.getAttribute&&a.getAttribute(b)||a.parentNode&&r(a.parentNode,b)},i={dir:r(a,"dir"),lang:r(a,"lang"),textDir:r(a,m)},q;for(q in i)i[q]||delete i[q]}for(var i={inherited:i},t,o;;)if(n)if(1!=n.nodeType)n=n.nextSibling;else if(t&&"script"==n.nodeName.toLowerCase())(w=n.getAttribute("type"))&&/^dojo\/\w/i.test(w)&&t.push(n),n=n.nextSibling;else if(o)n=n.nextSibling;else{var w=n.getAttribute(p)||n.getAttribute(h);q=n.firstChild;if(!w&&(!q||
3==q.nodeType&&!q.nextSibling))n=n.nextSibling;else{o=null;if(w){var y=n.getAttribute(s);t=y?[w].concat(y.split(/\s*,\s*/)):[w];try{o=D(t)}catch(x){}o||j.forEach(t,function(a){~a.indexOf("/")&&!f[a]&&(f[a]=!0,e[e.length]=a)});y=o&&!o.prototype._noScript?[]:null;i={types:t,ctor:o,parent:i,node:n,scripts:y};i.inherited=c(i);d.push(i)}else i={node:n,scripts:t,parent:i};n=q;t=y;o=o&&o.prototype.stopParser&&!b.template}}else{if(!i||!i.node)break;n=i.node.nextSibling;o=!1;i=i.parent;t=i.scripts}var C=new B;
e.length?(u("dojo-debug-messages")&&console.warn("WARNING: Modules being Auto-Required: "+e.join(", ")),k(e,function(){C.resolve(j.filter(d,function(a){if(!a.ctor)try{a.ctor=D(a.types)}catch(c){}for(var d=a.parent;d&&!d.types;)d=d.parent;var e=a.ctor&&a.ctor.prototype;a.instantiateChildren=!(e&&e.stopParser&&!b.template);a.instantiate=!d||d.instantiate&&d.instantiateChildren;return a.instantiate}))})):C.resolve(d);return C.promise},_require:function(a){var a=c.fromJson("{"+a.innerHTML+"}"),b=[],d=
[],e=new B,f;for(f in a)b.push(f),d.push(a[f]);k(d,function(){for(var a=0;a<b.length;a++)h.setObject(b[a],arguments[a]);e.resolve(arguments)});return e.promise},_scanAmd:function(a){var b=new B,c=b.promise;b.resolve(!0);var d=this;I("script[type='dojo/require']",a).forEach(function(a){c=c.then(function(){return d._require(a)});a.parentNode.removeChild(a)});return c},parse:function(a,c){var d;!c&&a&&a.rootNode?(c=a,d=c.rootNode):a&&h.isObject(a)&&!("nodeType"in a)?c=a:d=a;d=d?b.byId(d):f.body();var c=
c||{},e=c.template?{template:!0}:{},j=[],k=this,l=this._scanAmd(d,c).then(function(){return k.scan(d,c)}).then(function(a){return j=j.concat(k._instantiate(a,e,c))}).otherwise(function(a){console.error("dojo/parser::parse() error",a);throw a;});h.mixin(j,l);return j}};l.parser=G;a.parseOnLoad&&q(100,G,"parse");return G})},"dojo/_base/url":function(){define("dojo/_base/url",["./kernel"],function(k){var l=/^(([^:/?#]+):)?(\/\/([^/?#]*))?([^?#]*)(\?([^#]*))?(#(.*))?$/,h=/^((([^\[:]+):)?([^@]+)@)?(\[([^\]]+)\]|([^\[:]*))(:([0-9]+))?$/,
j=function(){for(var a=arguments,b=[a[0]],f=1;f<a.length;f++)if(a[f]){var e=new j(a[f]+""),b=new j(b[0]+"");if(""==e.path&&!e.scheme&&!e.authority&&!e.query){if(null!=e.fragment)b.fragment=e.fragment;e=b}else if(!e.scheme&&(e.scheme=b.scheme,!e.authority&&(e.authority=b.authority,"/"!=e.path.charAt(0)))){for(var b=(b.path.substring(0,b.path.lastIndexOf("/")+1)+e.path).split("/"),c=0;c<b.length;c++)"."==b[c]?c==b.length-1?b[c]="":(b.splice(c,1),c--):0<c&&!(1==c&&""==b[0])&&".."==b[c]&&".."!=b[c-1]&&
(c==b.length-1?(b.splice(c,1),b[c-1]=""):(b.splice(c-1,2),c-=2));e.path=b.join("/")}b=[];e.scheme&&b.push(e.scheme,":");e.authority&&b.push("//",e.authority);b.push(e.path);e.query&&b.push("?",e.query);e.fragment&&b.push("#",e.fragment)}this.uri=b.join("");a=this.uri.match(l);this.scheme=a[2]||(a[1]?"":null);this.authority=a[4]||(a[3]?"":null);this.path=a[5];this.query=a[7]||(a[6]?"":null);this.fragment=a[9]||(a[8]?"":null);if(null!=this.authority)a=this.authority.match(h),this.user=a[3]||null,this.password=
a[4]||null,this.host=a[6]||a[7],this.port=a[9]||null};j.prototype.toString=function(){return this.uri};return k._Url=j})}}});define("frontend/layer/mijit",[],1);