//>>built
require({cache:{"dijit/_Widget":function(){define("dijit/_Widget","dojo/aspect,dojo/_base/config,dojo/_base/connect,dojo/_base/declare,dojo/has,dojo/_base/kernel,dojo/_base/lang,dojo/query,dojo/ready,./registry,./_WidgetBase,./_OnDijitClickMixin,./_FocusMixin,dojo/uacss,./hccss".split(","),function(h,m,n,l,k,o,i,a,g,f,b,c,e){function j(){}function w(a){return function(b,f,e,q){return b&&"string"==typeof f&&b[f]==j?b.on(f.substring(2).toLowerCase(),i.hitch(e,q)):a.apply(n,arguments)}}h.around(n,"connect",
w);o.connect&&h.around(o,"connect",w);h=l("dijit._Widget",[b,c,e],{onClick:j,onDblClick:j,onKeyDown:j,onKeyPress:j,onKeyUp:j,onMouseDown:j,onMouseMove:j,onMouseOut:j,onMouseOver:j,onMouseLeave:j,onMouseEnter:j,onMouseUp:j,constructor:function(a){this._toConnect={};for(var b in a)this[b]===j&&(this._toConnect[b.replace(/^on/,"").toLowerCase()]=a[b],delete a[b])},postCreate:function(){this.inherited(arguments);for(var a in this._toConnect)this.on(a,this._toConnect[a]);delete this._toConnect},on:function(a,
b){return this[this._onMap(a)]===j?n.connect(this.domNode,a.toLowerCase(),this,b):this.inherited(arguments)},_setFocusedAttr:function(a){this._focused=a;this._set("focused",a)},setAttribute:function(a,b){o.deprecated(this.declaredClass+"::setAttribute(attr, value) is deprecated. Use set() instead.","","2.0");this.set(a,b)},attr:function(a,b){if(m.isDebug){var f=arguments.callee._ach||(arguments.callee._ach={}),j=(arguments.callee.caller||"unknown caller").toString();f[j]||(o.deprecated(this.declaredClass+
"::attr() is deprecated. Use get() or set() instead, called from "+j,"","2.0"),f[j]=!0)}return 2<=arguments.length||"object"===typeof a?this.set.apply(this,arguments):this.get(a)},getDescendants:function(){o.deprecated(this.declaredClass+"::getDescendants() is deprecated. Use getChildren() instead.","","2.0");return this.containerNode?a("[widgetId]",this.containerNode).map(f.byNode):[]},_onShow:function(){this.onShow()},onShow:function(){},onHide:function(){},onClose:function(){return!0}});k("dijit-legacy-requires")&&
g(0,function(){require(["dijit/_base"])});return h})},"dijit/_OnDijitClickMixin":function(){define("dijit/_OnDijitClickMixin","dojo/on,dojo/_base/array,dojo/keys,dojo/_base/declare,dojo/has,dojo/_base/unload,dojo/_base/window,./a11yclick".split(","),function(h,m,n,l,k,o,i,a){h=l("dijit._OnDijitClickMixin",null,{connect:function(g,f,b){return this.inherited(arguments,[g,"ondijitclick"==f?a:f,b])}});h.a11yclick=a;return h})},"dijit/a11yclick":function(){define("dijit/a11yclick","dojo/on,dojo/_base/array,dojo/keys,dojo/_base/declare,dojo/has,dojo/_base/unload,dojo/_base/window".split(","),
function(h,m,n,l,k,o,i){function a(a){return(a.keyCode===n.ENTER||a.keyCode===n.SPACE)&&!a.ctrlKey&&!a.shiftKey&&!a.altKey&&!a.metaKey}var g=null;k("dom-addeventlistener")?i.doc.addEventListener("keydown",function(a){g=a.target},!0):function(){var a=function(a){g=a.srcElement};i.doc.attachEvent("onkeydown",a);o.addOnWindowUnload(function(){i.doc.detachEvent("onkeydown",a)})}();return function(f,b){if(/input|button/i.test(f.nodeName))return h(f,"click",b);var c=[h(f,"keydown",function(b){if(a(b))g=
b.target,b.preventDefault()}),h(f,"keyup",function(b){a(b)&&b.target==g&&(g=null,h.emit(b.target,"click",{cancelable:!0,bubbles:!0}))}),h(f,"click",function(a){b.call(this,a)})];if(k("touch")){var e;c.push(h(f,"touchend",function(a){var b=a.target;e=setTimeout(function(){e=null;h.emit(b,"click",{cancelable:!0,bubbles:!0})},600)}),h(f,"click",function(){e&&clearTimeout(e)}))}return{remove:function(){m.forEach(c,function(a){a.remove()});e&&(clearTimeout(e),e=null)}}}})},"dijit/_FocusMixin":function(){define("dijit/_FocusMixin",
["./focus","./_WidgetBase","dojo/_base/declare","dojo/_base/lang"],function(h,m,n,l){l.extend(m,{focused:!1,onFocus:function(){},onBlur:function(){},_onFocus:function(){this.onFocus()},_onBlur:function(){this.onBlur()}});return n("dijit._FocusMixin",null,{_focusManager:h})})},"dijit/focus":function(){define("dijit/focus","dojo/aspect,dojo/_base/declare,dojo/dom,dojo/dom-attr,dojo/dom-construct,dojo/Evented,dojo/_base/lang,dojo/on,dojo/domReady,dojo/sniff,dojo/Stateful,dojo/_base/unload,dojo/_base/window,dojo/window,./a11y,./registry,./main".split(","),
function(h,m,n,l,k,o,i,a,g,f,b,c,e,j,w,x,t){var r=new (m([b,o],{curNode:null,activeStack:[],constructor:function(){var a=i.hitch(this,function(a){n.isDescendant(this.curNode,a)&&this.set("curNode",null);n.isDescendant(this.prevNode,a)&&this.set("prevNode",null)});h.before(k,"empty",a);h.before(k,"destroy",a)},registerIframe:function(a){return this.registerWin(a.contentWindow,a)},registerWin:function(a,b){var d=this,e=function(a){d._justMouseDowned=!0;setTimeout(function(){d._justMouseDowned=!1},0);
if(!f("ie")||!a||!(a.srcElement&&null==a.srcElement.parentNode))d._onTouchNode(b||a.target||a.srcElement,"mouse")},c=f("ie")?a.document.documentElement:a.document;if(c){if(f("ie")){a.document.body.attachEvent("onmousedown",e);var j=function(a){var c=a.srcElement.tagName.toLowerCase();"#document"==c||"body"==c||(w.isTabNavigable(a.srcElement)?d._onFocusNode(b||a.srcElement):d._onTouchNode(b||a.srcElement))};c.attachEvent("onfocusin",j);var g=function(a){d._onBlurNode(b||a.srcElement)};c.attachEvent("onfocusout",
g);return{remove:function(){a.document.detachEvent("onmousedown",e);c.detachEvent("onfocusin",j);c.detachEvent("onfocusout",g);c=null}}}c.body.addEventListener("mousedown",e,!0);c.body.addEventListener("touchstart",e,!0);var k=function(a){d._onFocusNode(b||a.target)};c.addEventListener("focus",k,!0);var i=function(a){d._onBlurNode(b||a.target)};c.addEventListener("blur",i,!0);return{remove:function(){c.body.removeEventListener("mousedown",e,!0);c.body.removeEventListener("touchstart",e,!0);c.removeEventListener("focus",
k,!0);c.removeEventListener("blur",i,!0);c=null}}}},_onBlurNode:function(){this._clearFocusTimer&&clearTimeout(this._clearFocusTimer);this._clearFocusTimer=setTimeout(i.hitch(this,function(){this.set("prevNode",this.curNode);this.set("curNode",null)}),0);if(!this._justMouseDowned)this._clearActiveWidgetsTimer&&clearTimeout(this._clearActiveWidgetsTimer),this._clearActiveWidgetsTimer=setTimeout(i.hitch(this,function(){delete this._clearActiveWidgetsTimer;this._setStack([])}),0)},_onTouchNode:function(a,
b){this._clearActiveWidgetsTimer&&(clearTimeout(this._clearActiveWidgetsTimer),delete this._clearActiveWidgetsTimer);var d=[];try{for(;a;){var c=l.get(a,"dijitPopupParent");if(c)a=x.byId(c).domNode;else if(a.tagName&&"body"==a.tagName.toLowerCase()){if(a===e.body())break;a=j.get(a.ownerDocument).frameElement}else{var f=a.getAttribute&&a.getAttribute("widgetId"),g=f&&x.byId(f);g&&!("mouse"==b&&g.get("disabled"))&&d.unshift(f);a=a.parentNode}}}catch(k){}this._setStack(d,b)},_onFocusNode:function(a){a&&
9!=a.nodeType&&(this._clearFocusTimer&&(clearTimeout(this._clearFocusTimer),delete this._clearFocusTimer),this._onTouchNode(a),a!=this.curNode&&(this.set("prevNode",this.curNode),this.set("curNode",a)))},_setStack:function(a,b){var d=this.activeStack;this.set("activeStack",a);for(var c=0;c<Math.min(d.length,a.length)&&!(d[c]!=a[c]);c++);for(var e,f=d.length-1;f>=c;f--)if(e=x.byId(d[f]))e._hasBeenBlurred=!0,e.set("focused",!1),e._focusManager==this&&e._onBlur(b),this.emit("widget-blur",e,b);for(f=
c;f<a.length;f++)if(e=x.byId(a[f]))e.set("focused",!0),e._focusManager==this&&e._onFocus(b),this.emit("widget-focus",e,b)},focus:function(a){if(a)try{a.focus()}catch(b){}}}));g(function(){var a=r.registerWin(j.get(e.doc));f("ie")&&c.addOnWindowUnload(function(){a&&(a.remove(),a=null)})});t.focus=function(a){r.focus(a)};for(var s in r)/^_/.test(s)||(t.focus[s]="function"==typeof r[s]?i.hitch(r,s):r[s]);r.watch(function(a,b,d){t.focus[a]=d});return r})},"dojo/window":function(){define("dojo/window",
"./_base/lang,./sniff,./_base/window,./dom,./dom-geometry,./dom-style".split(","),function(h,m,n,l,k,o){var i={getBox:function(a){var a=a||n.doc,g="BackCompat"==a.compatMode?n.body(a):a.documentElement,f=k.docScroll(a);if(m("touch"))var b=i.get(a),a=b.innerWidth||g.clientWidth,g=b.innerHeight||g.clientHeight;else a=g.clientWidth,g=g.clientHeight;return{l:f.x,t:f.y,w:a,h:g}},get:function(a){if(m("ie")&&i!==document.parentWindow){a.parentWindow.execScript("document._parentWindow = window;","Javascript");
var g=a._parentWindow;a._parentWindow=null;return g}return a.parentWindow||a.defaultView},scrollIntoView:function(a,g){try{var a=l.byId(a),f=a.ownerDocument||n.doc,b=n.body(f),c=f.documentElement||b.parentNode,e=m("ie"),j=m("webkit");if((!m("mozilla")&&!e&&!j&&!m("opera")||a==b||a==c)&&"undefined"!=typeof a.scrollIntoView)a.scrollIntoView(!1);else{var i="BackCompat"==f.compatMode,h=9<=e&&"frameElement"in a.ownerDocument.parentWindow?0<c.clientHeight&&0<c.clientWidth&&(0==b.clientHeight||0==b.clientWidth||
b.clientHeight>c.clientHeight||b.clientWidth>c.clientWidth)?c:b:i?b:c,j=j?b:h,t=h.clientWidth,r=h.clientHeight,s=!k.isBodyLtr(f),q=g||k.position(a),p=a.parentNode,f=function(a){return 6>=e||e&&i?!1:"fixed"==o.get(a,"position").toLowerCase()};if(!f(a))for(;p;){p==b&&(p=j);var d=k.position(p),D=f(p);if(p==j){d.w=t;d.h=r;j==c&&e&&s&&(d.x+=j.offsetWidth-d.w);if(0>d.x||!e)d.x=0;if(0>d.y||!e)d.y=0}else{var v=k.getPadBorderExtents(p);d.w-=v.w;d.h-=v.h;d.x+=v.l;d.y+=v.t;var u=p.clientWidth,y=d.w-u;if(0<u&&
0<y)d.w=u,d.x+=s&&(e||p.clientLeft>v.l)?y:0;u=p.clientHeight;y=d.h-u;if(0<u&&0<y)d.h=u}if(D){if(0>d.y)d.h+=d.y,d.y=0;if(0>d.x)d.w+=d.x,d.x=0;if(d.y+d.h>r)d.h=r-d.y;if(d.x+d.w>t)d.w=t-d.x}var z=q.x-d.x,A=q.y-Math.max(d.y,0),C=z+q.w-d.w,E=A+q.h-d.h;if(0<C*z){var B=Math[0>z?"max":"min"](z,C);if(s&&(8==e&&!i||9<=e))B=-B;q.x+=p.scrollLeft;p.scrollLeft+=B;q.x-=p.scrollLeft}0<E*A&&(q.y+=p.scrollTop,p.scrollTop+=Math[0>A?"max":"min"](A,E),q.y-=p.scrollTop);p=p!=j&&!D&&p.parentNode}}}catch(F){console.error("scrollIntoView: "+
F),a.scrollIntoView(!1)}}};h.setObject("dojo.window",i);return i})},"dijit/a11y":function(){define("dijit/a11y","dojo/_base/array,dojo/_base/config,dojo/_base/declare,dojo/dom,dojo/dom-attr,dojo/dom-style,dojo/sniff,./main".split(","),function(h,m,n,l,k,o,i,a){var g=a._isElementShown=function(a){var c=o.get(a);return"hidden"!=c.visibility&&"collapsed"!=c.visibility&&"none"!=c.display&&"hidden"!=k.get(a,"type")};a.hasDefaultTabStop=function(a){switch(a.nodeName.toLowerCase()){case "a":return k.has(a,
"href");case "area":case "button":case "input":case "object":case "select":case "textarea":return!0;case "iframe":var c;try{var e=a.contentDocument;if("designMode"in e&&"on"==e.designMode)return!0;c=e.body}catch(f){try{c=a.contentWindow.document.body}catch(g){return!1}}return c&&("true"==c.contentEditable||c.firstChild&&"true"==c.firstChild.contentEditable);default:return"true"==a.contentEditable}};var f=a.isTabNavigable=function(b){return k.get(b,"disabled")?!1:k.has(b,"tabIndex")?0<=k.get(b,"tabIndex"):
a.hasDefaultTabStop(b)};a._getTabNavigable=function(a){function c(a){return a&&"input"==a.tagName.toLowerCase()&&a.type&&"radio"==a.type.toLowerCase()&&a.name&&a.name.toLowerCase()}var e,j,h,l,m,n,o={},q=function(a){for(a=a.firstChild;a;a=a.nextSibling)if(!(1!=a.nodeType||i("ie")&&"HTML"!==a.scopeName||!g(a))){if(f(a)){var b=+k.get(a,"tabIndex");if(!k.has(a,"tabIndex")||0==b)e||(e=a),j=a;else if(0<b){if(!h||b<l)l=b,h=a;if(!m||b>=n)n=b,m=a}b=c(a);k.get(a,"checked")&&b&&(o[b]=a)}"SELECT"!=a.nodeName.toUpperCase()&&
q(a)}};g(a)&&q(a);return{first:o[c(e)]||e,last:o[c(j)]||j,lowest:o[c(h)]||h,highest:o[c(m)]||m}};a.getFirstInTabbingOrder=function(b,c){var e=a._getTabNavigable(l.byId(b,c));return e.lowest?e.lowest:e.first};a.getLastInTabbingOrder=function(b,c){var e=a._getTabNavigable(l.byId(b,c));return e.last?e.last:e.highest};return{hasDefaultTabStop:a.hasDefaultTabStop,isTabNavigable:a.isTabNavigable,_getTabNavigable:a._getTabNavigable,getFirstInTabbingOrder:a.getFirstInTabbingOrder,getLastInTabbingOrder:a.getLastInTabbingOrder}})},
"dojo/uacss":function(){define("dojo/uacss",["./dom-geometry","./_base/lang","./domReady","./sniff","./_base/window"],function(h,m,n,l,k){var o=k.doc.documentElement,k=l("ie"),i=l("opera"),a=Math.floor,g=l("ff"),f=h.boxModel.replace(/-/,""),i={dj_quirks:l("quirks"),dj_opera:i,dj_khtml:l("khtml"),dj_webkit:l("webkit"),dj_safari:l("safari"),dj_chrome:l("chrome"),dj_gecko:l("mozilla")};if(k)i.dj_ie=!0,i["dj_ie"+a(k)]=!0,i.dj_iequirks=l("quirks");g&&(i["dj_ff"+a(g)]=!0);i["dj_"+f]=!0;var b="",c;for(c in i)i[c]&&
(b+=c+" ");o.className=m.trim(o.className+" "+b);n(function(){if(!h.isBodyLtr()){var a="dj_rtl dijitRtl "+b.replace(/ /g,"-rtl ");o.className=m.trim(o.className+" "+a+"dj_rtl dijitRtl "+b.replace(/ /g,"-rtl "))}});return l})},"dijit/hccss":function(){define("dijit/hccss",["dojo/dom-class","dojo/hccss","dojo/domReady","dojo/_base/window"],function(h,m,n,l){n(function(){m("highcontrast")&&h.add(l.body(),"dijit_a11y")});return m})},"dojo/hccss":function(){define("dojo/hccss","require,./_base/config,./dom-class,./dom-style,./has,./domReady,./_base/window".split(","),
function(h,m,n,l,k,o,i){k.add("highcontrast",function(){var a=i.doc.createElement("div");a.style.cssText="border: 1px solid; border-color:red green; position: absolute; height: 5px; top: -999px;background-image: url("+(m.blankGif||h.toUrl("./resources/blank.gif"))+");";i.body().appendChild(a);var g=l.getComputedStyle(a),f=g.backgroundImage,g=g.borderTopColor==g.borderRightColor||f&&("none"==f||"url(invalid-url:)"==f);8>k("ie")?a.outerHTML="":i.body().removeChild(a);return g});o(function(){k("highcontrast")&&
n.add(i.body(),"dj_a11y")});return k})}}});define("frontend/layer/widget-extra",[],1);