//>>built
require({cache:{"dojo/parser":function(){define("dojo/parser","require,./_base/kernel,./_base/lang,./_base/array,./_base/config,./_base/html,./_base/window,./_base/url,./_base/json,./aspect,./date/stamp,./Deferred,./has,./query,./on,./ready".split(","),function(h,o,k,j,b,a,c,d,g,t,f,x,D,A,v,w){function y(a){var b=a._nameCaseMap,c=a.prototype;if(!b||b._extendCnt<C){var b=a._nameCaseMap={},q;for(q in c)"_"!==q.charAt(0)&&(b[q.toLowerCase()]=q);b._extendCnt=C}return b}function E(a){var b=a.join();if(!B[b]){for(var c=
[],q=0,d=a.length;q<d;q++){var f=a[q];c[c.length]=B[f]=B[f]||k.getObject(f)||~f.indexOf("/")&&h(f)}a=c.shift();B[b]=c.length?a.createSubclass?a.createSubclass(c):a.extend.apply(a,c):a}return B[b]}var C=0;t.after(k,"extend",function(){C++},!0);var B={},G={_clearCache:function(){C++;B={}},_functionFromScript:function(a,b){var c="",f="",d=a.getAttribute(b+"args")||a.getAttribute("args"),g=a.getAttribute("with"),d=(d||"").split(/\s*,\s*/);g&&g.length&&j.forEach(g.split(/\s*,\s*/),function(a){c+="with("+
a+"){";f+="}"});return new Function(d,c+a.innerHTML+f)},instantiate:function(a,b,c){var b=b||{},c=c||{},f=(c.scope||o._scopeName)+"Type",d="data-"+(c.scope||o._scopeName)+"-",g=d+"type",t=d+"mixins",n=[];j.forEach(a,function(a){var c=f in b?b[f]:a.getAttribute(g)||a.getAttribute(f);if(c){var d=a.getAttribute(t),c=d?[c].concat(d.split(/\s*,\s*/)):[c];n.push({node:a,types:c})}});return this._instantiate(n,b,c)},_instantiate:function(a,b,c){a=j.map(a,function(a){var f=a.ctor||E(a.types);if(!f)throw Error("Unable to resolve constructor for: '"+
a.types.join()+"'");return this.construct(f,a.node,b,c,a.scripts,a.inherited)},this);!b._started&&!c.noStart&&j.forEach(a,function(a){"function"===typeof a.startup&&!a._started&&a.startup()});return a},construct:function(a,b,c,q,z,u){var I;var x=a&&a.prototype,q=q||{},n={};q.defaults&&k.mixin(n,q.defaults);u&&k.mixin(n,u);var h;D("dom-attributes-explicit")?h=b.attributes:D("dom-attributes-specified-flag")?h=j.filter(b.attributes,function(a){return a.specified}):(u=(/^input$|^img$/i.test(b.nodeName)?
b:b.cloneNode(!1)).outerHTML.replace(/=[^\s"']+|="[^"]*"|='[^']*'/g,"").replace(/^\s*<[a-zA-Z0-9]*\s*/,"").replace(/\s*>.*$/,""),h=j.map(u.split(/\s+/),function(a){var c=a.toLowerCase();return{name:a,value:"LI"==b.nodeName&&"value"==a||"enctype"==c?b.getAttribute(c):b.getAttributeNode(c).value}}));var i=q.scope||o._scopeName,u="data-"+i+"-",l={};"dojo"!==i&&(l[u+"props"]="data-dojo-props",l[u+"type"]="data-dojo-type",l[u+"mixins"]="data-dojo-mixins",l[i+"type"]="dojoType",l[u+"id"]="data-dojo-id");
for(var i=0,e,w=[],F,p;e=h[i++];){var m=e.name,r=m.toLowerCase();e=e.value;switch(l[r]||r){case "data-dojo-type":case "dojotype":case "data-dojo-mixins":break;case "data-dojo-props":p=e;break;case "data-dojo-id":case "jsid":F=e;break;case "data-dojo-attach-point":case "dojoattachpoint":n.dojoAttachPoint=e;break;case "data-dojo-attach-event":case "dojoattachevent":n.dojoAttachEvent=e;break;case "class":n["class"]=b.className;break;case "style":n.style=b.style&&b.style.cssText;break;default:if(m in
x||(m=y(a)[r]||m),m in x)switch(typeof x[m]){case "string":n[m]=e;break;case "number":n[m]=e.length?Number(e):NaN;break;case "boolean":n[m]="false"!=e.toLowerCase();break;case "function":n[m]=""===e||-1!=e.search(/[^\w\.]+/i)?new Function(e):k.getObject(e,!1)||new Function(e);w.push(m);break;default:r=x[m],n[m]=r&&"length"in r?e?e.split(/\s*,\s*/):[]:r instanceof Date?""==e?new Date(""):"now"==e?new Date:f.fromISOString(e):r instanceof d?o.baseUrl+e:g.fromJson(e)}else n[m]=e}}for(i=0;i<w.length;i++)h=
w[i].toLowerCase(),b.removeAttribute(h),b[h]=null;if(p)try{p=g.fromJson.call(q.propsThis,"{"+p+"}"),k.mixin(n,p)}catch(H){throw Error(H.toString()+" in data-dojo-props='"+p+"'");}k.mixin(n,c);z||(z=a&&(a._noScript||x._noScript)?[]:A("> script[type^='dojo/']",b));c=[];q=[];p=[];w=[];if(z)for(i=0;i<z.length;i++){var s=z[i];b.removeChild(s);h=s.getAttribute(u+"event")||s.getAttribute("event");l=s.getAttribute(u+"prop");m=s.getAttribute(u+"method");r=s.getAttribute(u+"advice");e=s.getAttribute("type");
s=this._functionFromScript(s,u);h?"dojo/connect"==e?c.push({method:h,func:s}):"dojo/on"==e?w.push({event:h,func:s}):n[h]=s:"dojo/aspect"==e?c.push({method:m,advice:r,func:s}):"dojo/watch"==e?p.push({prop:l,func:s}):q.push(s)}I=(z=a.markupFactory||x.markupFactory)?z(n,b,a):new a(n,b),a=I;F&&k.setObject(F,a);for(i=0;i<c.length;i++)t[c[i].advice||"after"](a,c[i].method,k.hitch(a,c[i].func),!0);for(i=0;i<q.length;i++)q[i].call(a);for(i=0;i<p.length;i++)a.watch(p[i].prop,p[i].func);for(i=0;i<w.length;i++)v(a,
w[i].event,w[i].func);return a},scan:function(a,b){function c(a){if(!a.inherited){a.inherited={};var b=a.node,f=c(a.parent),b={dir:b.getAttribute("dir")||f.dir,lang:b.getAttribute("lang")||f.lang,textDir:b.getAttribute(i)||f.textDir},d;for(d in b)b[d]&&(a.inherited[d]=b[d])}return a.inherited}var f=[],d=[],g={},t=(b.scope||o._scopeName)+"Type",n="data-"+(b.scope||o._scopeName)+"-",w=n+"type",i=n+"textdir",n=n+"mixins",l=a.firstChild,e=b.inherited;if(!e){var k=function(a,b){return a.getAttribute&&
a.getAttribute(b)||a.parentNode&&k(a.parentNode,b)},e={dir:k(a,"dir"),lang:k(a,"lang"),textDir:k(a,i)},v;for(v in e)e[v]||delete e[v]}for(var e={inherited:e},p,m;;)if(l)if(1!=l.nodeType)l=l.nextSibling;else if(p&&"script"==l.nodeName.toLowerCase())(r=l.getAttribute("type"))&&/^dojo\/\w/i.test(r)&&p.push(l),l=l.nextSibling;else if(m)l=l.nextSibling;else{var r=l.getAttribute(w)||l.getAttribute(t);v=l.firstChild;if(!r&&(!v||3==v.nodeType&&!v.nextSibling))l=l.nextSibling;else{m=null;if(r){var y=l.getAttribute(n);
p=y?[r].concat(y.split(/\s*,\s*/)):[r];try{m=E(p)}catch(s){}m||j.forEach(p,function(a){~a.indexOf("/")&&!g[a]&&(g[a]=!0,d[d.length]=a)});y=m&&!m.prototype._noScript?[]:null;e={types:p,ctor:m,parent:e,node:l,scripts:y};e.inherited=c(e);f.push(e)}else e={node:l,scripts:p,parent:e};l=v;p=y;m=m&&m.prototype.stopParser&&!b.template}}else{if(!e||!e.node)break;l=e.node.nextSibling;m=!1;e=e.parent;p=e.scripts}var A=new x;d.length?(D("dojo-debug-messages")&&console.warn("WARNING: Modules being Auto-Required: "+
d.join(", ")),h(d,function(){A.resolve(j.filter(f,function(a){if(!a.ctor)try{a.ctor=E(a.types)}catch(c){}for(var f=a.parent;f&&!f.types;)f=f.parent;var d=a.ctor&&a.ctor.prototype;a.instantiateChildren=!(d&&d.stopParser&&!b.template);a.instantiate=!f||f.instantiate&&f.instantiateChildren;return a.instantiate}))})):A.resolve(f);return A.promise},_require:function(a){var a=g.fromJson("{"+a.innerHTML+"}"),b=[],c=[],f=new x,d;for(d in a)b.push(d),c.push(a[d]);h(c,function(){for(var a=0;a<b.length;a++)k.setObject(b[a],
arguments[a]);f.resolve(arguments)});return f.promise},_scanAmd:function(a){var b=new x,c=b.promise;b.resolve(!0);var f=this;A("script[type='dojo/require']",a).forEach(function(a){c=c.then(function(){return f._require(a)});a.parentNode.removeChild(a)});return c},parse:function(b,f){var d;!f&&b&&b.rootNode?(f=b,d=f.rootNode):b&&k.isObject(b)&&!("nodeType"in b)?f=b:d=b;d=d?a.byId(d):c.body();var f=f||{},g=f.template?{template:!0}:{},h=[],t=this,v=this._scanAmd(d,f).then(function(){return t.scan(d,f)}).then(function(a){return h=
h.concat(t._instantiate(a,g,f))}).otherwise(function(a){console.error("dojo/parser::parse() error",a);throw a;});k.mixin(h,v);return h}};o.parser=G;b.parseOnLoad&&w(100,G,"parse");return G})},"dojo/_base/url":function(){define("dojo/_base/url",["./kernel"],function(h){var o=/^(([^:/?#]+):)?(\/\/([^/?#]*))?([^?#]*)(\?([^#]*))?(#(.*))?$/,k=/^((([^\[:]+):)?([^@]+)@)?(\[([^\]]+)\]|([^\[:]*))(:([0-9]+))?$/,j=function(){for(var b=arguments,a=[b[0]],c=1;c<b.length;c++)if(b[c]){var d=new j(b[c]+""),a=new j(a[0]+
"");if(""==d.path&&!d.scheme&&!d.authority&&!d.query){if(null!=d.fragment)a.fragment=d.fragment;d=a}else if(!d.scheme&&(d.scheme=a.scheme,!d.authority&&(d.authority=a.authority,"/"!=d.path.charAt(0)))){for(var a=(a.path.substring(0,a.path.lastIndexOf("/")+1)+d.path).split("/"),g=0;g<a.length;g++)"."==a[g]?g==a.length-1?a[g]="":(a.splice(g,1),g--):0<g&&!(1==g&&""==a[0])&&".."==a[g]&&".."!=a[g-1]&&(g==a.length-1?(a.splice(g,1),a[g-1]=""):(a.splice(g-1,2),g-=2));d.path=a.join("/")}a=[];d.scheme&&a.push(d.scheme,
":");d.authority&&a.push("//",d.authority);a.push(d.path);d.query&&a.push("?",d.query);d.fragment&&a.push("#",d.fragment)}this.uri=a.join("");b=this.uri.match(o);this.scheme=b[2]||(b[1]?"":null);this.authority=b[4]||(b[3]?"":null);this.path=b[5];this.query=b[7]||(b[6]?"":null);this.fragment=b[9]||(b[8]?"":null);if(null!=this.authority)b=this.authority.match(k),this.user=b[3]||null,this.password=b[4]||null,this.host=b[6]||b[7],this.port=b[9]||null};j.prototype.toString=function(){return this.uri};
return h._Url=j})},"dijit/form/_FormWidget":function(){define("dijit/form/_FormWidget","dojo/_base/declare,dojo/has,dojo/_base/kernel,dojo/ready,../_Widget,../_CssStateMixin,../_TemplatedMixin,./_FormWidgetMixin".split(","),function(h,o,k,j,b,a,c,d){o("dijit-legacy-requires")&&j(0,function(){require(["dijit/form/_FormValueWidget"])});return h("dijit.form._FormWidget",[b,c,a,d],{setDisabled:function(a){k.deprecated("setDisabled("+a+") is deprecated. Use set('disabled',"+a+") instead.","","2.0");this.set("disabled",
a)},setValue:function(a){k.deprecated("dijit.form._FormWidget:setValue("+a+") is deprecated.  Use set('value',"+a+") instead.","","2.0");this.set("value",a)},getValue:function(){k.deprecated(this.declaredClass+"::getValue() is deprecated. Use get('value') instead.","","2.0");return this.get("value")},postMixInProperties:function(){this.nameAttrSetting=this.name?'name="'+this.name.replace(/"/g,"&quot;")+'"':"";this.inherited(arguments)},_setTypeAttr:null})})},"dijit/_CssStateMixin":function(){define("dijit/_CssStateMixin",
"dojo/_base/array,dojo/_base/declare,dojo/dom,dojo/dom-class,dojo/has,dojo/_base/lang,dojo/on,dojo/domReady,dojo/_base/window,./registry".split(","),function(h,o,k,j,b,a,c,d,g,t){o=o("dijit._CssStateMixin",[],{cssStateNodes:{},hovering:!1,active:!1,_applyAttributes:function(){this.inherited(arguments);h.forEach("disabled,readOnly,checked,selected,focused,state,hovering,active,_opened".split(","),function(b){this.watch(b,a.hitch(this,"_setStateClass"))},this);for(var b in this.cssStateNodes)this._trackMouseState(this[b],
this.cssStateNodes[b]);this._trackMouseState(this.domNode,this.baseClass);this._setStateClass()},_cssMouseEvent:function(a){if(!this.disabled)switch(a.type){case "mouseover":this._set("hovering",!0);this._set("active",this._mouseDown);break;case "mouseout":this._set("hovering",!1);this._set("active",!1);break;case "mousedown":case "touchstart":this._set("active",!0);break;case "mouseup":case "touchend":this._set("active",!1)}},_setStateClass:function(){function a(c){b=b.concat(h.map(b,function(a){return a+
c}),"dijit"+c)}var b=this.baseClass.split(" ");this.isLeftToRight()||a("Rtl");var c="mixed"==this.checked?"Mixed":this.checked?"Checked":"";this.checked&&a(c);this.state&&a(this.state);this.selected&&a("Selected");this._opened&&a("Opened");this.disabled?a("Disabled"):this.readOnly?a("ReadOnly"):this.active?a("Active"):this.hovering&&a("Hover");this.focused&&a("Focused");var c=this.stateNode||this.domNode,d={};h.forEach(c.className.split(" "),function(a){d[a]=!0});"_stateClasses"in this&&h.forEach(this._stateClasses,
function(a){delete d[a]});h.forEach(b,function(a){d[a]=!0});var g=[],t;for(t in d)g.push(t);c.className=g.join(" ");this._stateClasses=b},_subnodeCssMouseEvent:function(a,b,c){function d(c){j.toggle(a,b+"Active",c)}if(!this.disabled&&!this.readOnly)switch(c.type){case "mouseover":j.toggle(a,b+"Hover",!0);break;case "mouseout":j.toggle(a,b+"Hover",!1);d(!1);break;case "mousedown":case "touchstart":d(!0);break;case "mouseup":case "touchend":d(!1);break;case "focus":case "focusin":j.toggle(a,b+"Focused",
!0);break;case "blur":case "focusout":j.toggle(a,b+"Focused",!1)}},_trackMouseState:function(a,b){a._cssState=b}});d(function(){function a(b){if(!k.isDescendant(b.relatedTarget,b.target))for(var c=b.target;c&&c!=b.relatedTarget;c=c.parentNode)if(c._cssState){var d=t.getEnclosingWidget(c);d&&(c==d.domNode?d._cssMouseEvent(b):d._subnodeCssMouseEvent(c,c._cssState,b))}}function d(b){b.target=b.srcElement;a(b)}var j=g.body(),o=(b("touch")?[]:["mouseover","mouseout"]).concat(["mousedown","touchstart",
"mouseup","touchend"]);h.forEach(o,function(b){j.addEventListener?j.addEventListener(b,a,!0):j.attachEvent("on"+b,d)});c(j,"focusin, focusout",function(a){var b=a.target;b._cssState&&!b.getAttribute("widgetId")&&t.getEnclosingWidget(b)._subnodeCssMouseEvent(b,b._cssState,a)})});return o})},"dijit/form/_FormWidgetMixin":function(){define("dijit/form/_FormWidgetMixin","dojo/_base/array,dojo/_base/declare,dojo/dom-attr,dojo/dom-style,dojo/_base/lang,dojo/mouse,dojo/sniff,dojo/window,../a11y".split(","),
function(h,o,k,j,b,a,c,d,g){return o("dijit.form._FormWidgetMixin",null,{name:"",alt:"",value:"",type:"text","aria-label":"focusNode",tabIndex:"0",_setTabIndexAttr:"focusNode",disabled:!1,intermediateChanges:!1,scrollOnFocus:!0,_setIdAttr:"focusNode",_setDisabledAttr:function(a){this._set("disabled",a);k.set(this.focusNode,"disabled",a);this.valueNode&&k.set(this.valueNode,"disabled",a);this.focusNode.setAttribute("aria-disabled",a?"true":"false");a?(this._set("hovering",!1),this._set("active",!1),
a="tabIndex"in this.attributeMap?this.attributeMap.tabIndex:"_setTabIndexAttr"in this?this._setTabIndexAttr:"focusNode",h.forEach(b.isArray(a)?a:[a],function(a){a=this[a];c("webkit")||g.hasDefaultTabStop(a)?a.setAttribute("tabIndex","-1"):a.removeAttribute("tabIndex")},this)):""!=this.tabIndex&&this.set("tabIndex",this.tabIndex)},_onFocus:function(a){if("mouse"==a&&this.isFocusable())var b=this.connect(this.focusNode,"onfocus",function(){this.disconnect(c);this.disconnect(b)}),c=this.connect(this.ownerDocumentBody,
"onmouseup",function(){this.disconnect(c);this.disconnect(b);this.focused&&this.focus()});this.scrollOnFocus&&this.defer(function(){d.scrollIntoView(this.domNode)});this.inherited(arguments)},isFocusable:function(){return!this.disabled&&this.focusNode&&"none"!=j.get(this.domNode,"display")},focus:function(){if(!this.disabled&&this.focusNode.focus)try{this.focusNode.focus()}catch(a){}},compare:function(a,b){return"number"==typeof a&&"number"==typeof b?isNaN(a)&&isNaN(b)?0:a-b:a>b?1:a<b?-1:0},onChange:function(){},
_onChangeActive:!1,_handleOnChange:function(a,b){if(void 0==this._lastValueReported&&(null===b||!this._onChangeActive))this._resetValue=this._lastValueReported=a;this._pendingOnChange=this._pendingOnChange||typeof a!=typeof this._lastValueReported||0!=this.compare(a,this._lastValueReported);if((this.intermediateChanges||b||void 0===b)&&this._pendingOnChange)if(this._lastValueReported=a,this._pendingOnChange=!1,this._onChangeActive)this._onChangeHandle&&this._onChangeHandle.remove(),this._onChangeHandle=
this.defer(function(){this._onChangeHandle=null;this.onChange(a)})},create:function(){this.inherited(arguments);this._onChangeActive=!0},destroy:function(){this._onChangeHandle&&(this._onChangeHandle.remove(),this.onChange(this._lastValueReported));this.inherited(arguments)}})})},"dijit/form/_ButtonMixin":function(){define("dijit/form/_ButtonMixin",["dojo/_base/declare","dojo/dom","dojo/_base/event","../registry"],function(h,o,k,j){return h("dijit.form._ButtonMixin",null,{label:"",type:"button",_onClick:function(b){if(this.disabled)return k.stop(b),
!1;var a=!1===this.onClick(b);if(!a&&"submit"==this.type&&!(this.valueNode||this.focusNode).form)for(var c=this.domNode;c.parentNode;c=c.parentNode){var d=j.byNode(c);if(d&&"function"==typeof d._onSubmit){d._onSubmit(b);a=!0;break}}a&&b.preventDefault();return!a},postCreate:function(){this.inherited(arguments);o.setSelectable(this.focusNode,!1)},onClick:function(){return!0},_setLabelAttr:function(b){this._set("label",b);var a=this.containerNode||this.focusNode;a.innerHTML=b;this.textDir&&this.applyTextDir(a)}})})},
"dojo/NodeList-traverse":function(){define("dojo/NodeList-traverse",["./query","./_base/lang","./_base/array"],function(h,o,k){var j=h.NodeList;o.extend(j,{_buildArrayFromCallback:function(b){for(var a=[],c=0;c<this.length;c++){var d=b.call(this[c],this[c],a);d&&(a=a.concat(d))}return a},_getUniqueAsNodeList:function(b){for(var a=[],c=0,d;d=b[c];c++)1==d.nodeType&&-1==k.indexOf(a,d)&&a.push(d);return this._wrap(a,null,this._NodeListCtor)},_getUniqueNodeListWithParent:function(b,a){var c=this._getUniqueAsNodeList(b),
c=a?h._filterResult(c,a):c;return c._stash(this)},_getRelatedUniqueNodes:function(b,a){return this._getUniqueNodeListWithParent(this._buildArrayFromCallback(a),b)},children:function(b){return this._getRelatedUniqueNodes(b,function(a){return o._toArray(a.childNodes)})},closest:function(b,a){return this._getRelatedUniqueNodes(null,function(c){do if(h._filterResult([c],b,a).length)return c;while(c!=a&&(c=c.parentNode)&&1==c.nodeType);return null})},parent:function(b){return this._getRelatedUniqueNodes(b,
function(a){return a.parentNode})},parents:function(b){return this._getRelatedUniqueNodes(b,function(a){for(var b=[];a.parentNode;)a=a.parentNode,b.push(a);return b})},siblings:function(b){return this._getRelatedUniqueNodes(b,function(a){for(var b=[],d=a.parentNode&&a.parentNode.childNodes,g=0;g<d.length;g++)d[g]!=a&&b.push(d[g]);return b})},next:function(b){return this._getRelatedUniqueNodes(b,function(a){for(a=a.nextSibling;a&&1!=a.nodeType;)a=a.nextSibling;return a})},nextAll:function(b){return this._getRelatedUniqueNodes(b,
function(a){for(var b=[];a=a.nextSibling;)1==a.nodeType&&b.push(a);return b})},prev:function(b){return this._getRelatedUniqueNodes(b,function(a){for(a=a.previousSibling;a&&1!=a.nodeType;)a=a.previousSibling;return a})},prevAll:function(b){return this._getRelatedUniqueNodes(b,function(a){for(var b=[];a=a.previousSibling;)1==a.nodeType&&b.push(a);return b})},andSelf:function(){return this.concat(this._parent)},first:function(){return this._wrap(this[0]&&[this[0]]||[],this)},last:function(){return this._wrap(this.length?
[this[this.length-1]]:[],this)},even:function(){return this.filter(function(b,a){return 0!=a%2})},odd:function(){return this.filter(function(b,a){return 0==a%2})}});return j})}}});define("frontend/layer/misc",[],1);